version: '3.7'
services: 
    app:
        build:
            context: LineupApp
            target: base
        volumes:
            - ./LineupApp:/app
        labels:
            - "traefik.http.routers.ui.rule=PathPrefix(`/`)"
            - "traefik.http.services.ui.loadbalancer.server.port=3000"
        stdin_open: true
    reverse-proxy:
        image: traefik:2.2
        command: --providers.docker --api.insecure=true
        ports:
            - "9000:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock