version: '3.7'
services: 
    app_prod:
        build: 
            context: LineupApp
            target: publish
        ports: 
            - "8000:80"
    api_prod:
        build:
            context: LineupApi
            target: publish
        ports: 
            - "5000:80"
        # env_file:
        #     - "app.env"
    db_prod:
        image: postgres:12.2
        ports:
            - "15432:5432"
        environment:
            - POSTGRES_DB=lineup_prod
            - POSTGRES_PASSWORD=xmipRww8q3VNM
            - POSTGRES_USER=lineup_user
